### ISSUE TITLE
How to change contact's email?

### ISSUE THREAD

**Issue by powerman** [sendinblue/APIv3-go-library#10]
If our customer change his email we need to update related SIB contact.
I didn't see a way to use SIB contact ID (mentioned in models.GetContactDetails) to update contact's email (everything else uses email as ID), so I need to delete contact with old email and add new contact, but I didn't see any methods in this package to delete contact.

**Comment by powerman** [comment]
@jain-raunak Can you please explain why did you close this issue?

**Comment by jain-raunak** [comment]
Hi @powerman 
Here, we have updated the Go wrapper with all the new structure and workflow. You can use the updated version of this package as v2.0.1.
In this version all such issues are resolved.

Thankyou
