### ISSUE TITLE
Transactional E-Mail by Template ID with Parameters ?

### ISSUE THREAD

**Issue by sPooKee** [sendinblue/APIv3-go-library#11]
https://developers.sendinblue.com/v3.0/reference#sendtransacemail

- If I use `NewSendTransacEmailParams()` I'm not able to specify a TemplateID
- If I use `NewSendTemplateParams()` I can send only "attributes" which are not available in the Template `{{ params.TEST }}`

`TEST` is saved as Transactional Attribute

**Comment by abdulrehmank** [comment]
Hey @sPooKee Did your issue got resolved?

I am also trying to use this library and want to know about the usability of the library.

**Comment by sPooKee** [comment]
hi @abdulrehmank,

unfortunatly not ;-) I switch to a `http.Request` and connect to the API directly...

**Comment by abdulrehmank** [comment]
Thanks Spookee for your prompt update. I extremely appreciate it. 
I am also trying to use this Library and after integration I found the library itself gives errors for few basic params. 
So, I also won't be relying on this as such and move to API version of it. Hope it is a reliable one.
