### ISSUE TITLE
Cannot unmarshal bool into Go struct field GetContacts.contacts of type string

### ISSUE THREAD

**Issue by Jgiron455** [sendinblue/APIv3-go-library#14]
https://github.com/sendinblue/APIv3-go-library/blob/2badbd8ca804fdd5b4acd6daa54422f47af1cefb/client/contacts/contacts_client.go#L123

Tried this out with a plain params of NewGetContactsParams to retrieve all of our contacts, but gotten the following error;

Error: json: cannot unmarshal bool into Go struct field GetContacts.contacts of type string

**Comment by marvinhosea** [comment]
Lol @jain-raunak decide to close the issue without any answer or update

**Comment by jain-raunak** [comment]
Hi @marvinhosea 
This issue was registered on 06th June 2020 and after that we did released the new package **v2.0.1** on 31st March 2021 resolving this error. 
FYI, we are working to upgrade the package again and soon release it, kindly let us know if I can help you with anything.
Cheers!
