### ISSUE TITLE
Unable to use v2.0.1 in go.mod

### ISSUE THREAD

**Issue by kbokarius** [sendinblue/APIv3-go-library#24]
Added to go.mod:

```
github.com/sendinblue/APIv3-go-library/v2 v2.0.1
```

Getting this error with `go mod download`:

```
go: github.com/sendinblue/APIv3-go-library/v2@v2.0.1: go.mod has non-.../v2 module path "github.com/sendinblue/APIv3-go-library" (and .../v2/go.mod does not exist) at revision v2.0.1
```

**Comment by jain-raunak** [comment]
Hi @kbokarius 
Here, you can follow the given steps:
1. Make sure you have set GO111MODULES, if by mistake it is off then please make it enable.
 **go env -w GO111MODULE=on**
2. go to your work directory in terminal and run:
- **go mod init <filename/module name>**
- **go mod tidy**
eg, suppose your directory name is "TestProject" and inside this having a module directory as myProject having go files.
Structure would be like:
--TestProject
      --myProject
         - *.go
         - *.go
   Then command would be like **go mod init myProject** and then **go mod tidy**

**Comment by kbokarius** [comment]
It seems to be working now. Thanks @jain-raunak. Love the customer support you guys provide!
