### ISSUE TITLE
Unable to download v2.0.1 or use v1.5.0

### ISSUE THREAD

**Issue by Wazazaby** [sendinblue/APIv3-go-library#28]
Hi,

I followed the installation procedure described [here](https://github.com/sendinblue/APIv3-go-library#installation--usage), and it doesn't work.

Only the latest tag of the v1 library can be imported (v1.5.0) because the [go.mod's](https://github.com/sendinblue/APIv3-go-library/blob/master/go.mod) module path is missing the `/v2` suffix on the latest tag (v2.0.1). 

And as shown in the installation procedure "getting started" example, the v1 library does not provide a `github.com/sendinblue/APIv3-go-library/lib` package so it can't be used.

Here's the output of a `go mod tidy` after running `go get github.com/sendinblue/APIv3-go-library` :
```
go: finding module for package github.com/sendinblue/APIv3-go-library/lib
my/repository imports
        github.com/sendinblue/APIv3-go-library/lib: module github.com/sendinblue/APIv3-go-library@latest found (v1.5.0), but does not contain package github.com/sendinblue/APIv3-go-library/lib
```

And here's the result of running `go get github.com/sendinblue/APIv3-go-library@v2.0.1` (forcing v2.0.1 tag) :
```
go: github.com/sendinblue/APIv3-go-library@v2.0.1: invalid version: module contains a go.mod file, so module path must match major version ("github.com/sendinblue/APIv3-go-library/v2")
```

Thanks.

PS: see issue #24 I believe it's the same problem

**Comment by iwittkau** [comment]
I think your title is misleading, I can `go get` and use `v1.5.0`.

The v2 problem I can reproduce: Go refuses to import the latests tag because the versioning is not set up correctly.

Go expects `v2` to be present in the import path for versions that are tagged with >=v2.0.0, see https://go.dev/blog/v2-go-modules.

**Comment by Wazazaby** [comment]
I said that you can't use the `v1.5.0`, not that you can't download it. It doesn't provide a `/lib` (`github.com/sendinblue/APIv3-go-library/lib`) package like shown in the docs (which was likely updated for the v2).

**Comment by iwittkau** [comment]
Yes, you have to look for the example in `v1.5.0`: https://github.com/sendinblue/APIv3-go-library/blob/v1.5.0/test/api_test.go

This is referred to from the `v1.5.0` README. The package structure was different then.

**Comment by Wazazaby** [comment]
You're right. Still, the v2 can't be used as is, and I would prefer to integrate an up to date version of the library in my service.

**Comment by jain-raunak** [comment]
Hi @Wazazaby @iwittkau 
Apologies for the versioning issue, actually there is no backward compatibility to older version v1.5.0 and you have to use the latest version v2.0.1 only. By removing and regenerating go.mod and go.sum file doesn't help you?
1. Delete existing go.mod and go.sum
2. again generate these files
- go mod init <filename/module name>
- go mod tidy 

Also we are working to upgrade the package with all the fixes of wrong datatype, it would be done by this June. Thankyou for the patience.

**Comment by Wazazaby** [comment]
Hi Jain. 
I cloned the library on my machine and fixed the versioning issues. With a `replace` directive pointing to this local version in my `go.mod`, it's working fine for now, so no worries.
