### ISSUE TITLE
Boolean model values can't be set to false

### ISSUE THREAD

**Issue by rafl** [sendinblue/APIv3-go-library#33]
Generated models containing boolean parameters currently look like this:

```
type UpdateContact struct {
    ...
    EmailBlacklisted bool `json:"emailBlacklisted,omitempty"`
    ...
}
```

Serializing `UpdateContact{EmailBlacklisted: false}` via `encoding/json` will produce `{}` as a request body, causing a 400 error. Worse yet, if there were other non-omitted fields in the structure, the request will succeed while silently not updating the boolean property.

It seems like most boolean properties should probably be encoded as `*bool` within the go models.

**Comment by jain-raunak** [comment]
Hi @rafl 
This issue has been fixed on the latest version v2.1.2, please verify.
Thanks!
