### ISSUE TITLE
ListAPI modifiedAt field is missing

### ISSUE THREAD

**Issue by denkhaus** [sendinblue/APIv3-go-library#34]
Hi,

in the ListApi it seems, the `modifiedAt  time.Time` field is missing in the `GetExtendedList` struct. I would assume, if we can Update a list by  `UpdateList(ctx context.Context, listId int64, updateList lib.UpdateList) (*http.Response, error)` we must be able to retrieve this value to distinguish between valid or stale client side data. Or do I miss something?
Same for FolderAPI...

**Comment by jain-raunak** [comment]
Hello @denkhaus 
Thanks for pointing this out. Right now we are not providing modifiedAt in the [response](https://developers.sendinblue.com/reference/getlist-1) as per current structure . But taken your suggestion into consideration and update it soon once confirmed by the team.
